name: Generate Next Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 
          # Token for robot account @equinix-homebrew-tap, which can publish
          # to metal-cli and homebrew-tap GH repos
          GITHUB_TOKEN: ${{ secrets.GH_HOMEBREW_TAP_TOKEN }}
